tosca_definitions_version: cloudify_dsl_1_3

plugins:
  solo:
    executor: central_deployment_agent
    source: https://github.com/NiltonDuarte/CloudifyPlugin/archive/master.zip
    package_name: solo_plugin
    package_version: '0.0'

data_types:
  cloudify.solo.types.configuration:
    properties:
      server_ip:
        type: string
        required: false
      server_port:
        type: string
        required: false
      username:
        type: string
        required: false
      password:
        type: string
        required: false

node_types:

  cloudify.solo.nodes.VirtualNetwork:
    derived_from: cloudify.nodes.Root
    properties: 
      solo_config:
        type: cloudify.solo.types.configuration     
      vNetworkName:
        type: string 
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: solo.solo_plugin.network.create
        delete:
          implementation: solo.solo_plugin.network.delete

  cloudify.solo.nodes.VirtualSwitch:
    derived_from: cloudify.nodes.Network
    properties: 
      solo_config:
        type: cloudify.solo.types.configuration
        required: false 
      vNetworkName:
        type: string  
        required: false       
      datapathId: 
        type: string
      controllerIp: 
        type: string
      controllerPort: 
        type: string
        default: "6633"
      openflowVersion: 
        type: string
        default: "OF_13"
      physicalDevice: 
        type: string
     
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: solo.solo_plugin.switch.create
        delete:
          implementation: solo.solo_plugin.switch.delete          
                 
  cloudify.solo.nodes.VirtualPort:
    derived_from: cloudify.nodes.Port
    properties: 
      solo_config:
        type: cloudify.solo.types.configuration
        required: false
      vNetworkName:
        type: string 
        required: false
      datapathId:
        type: string
        required: false       
      virtualPortNumber:
        type: string        
      physicalPortName:
        type: string        
      bindingType:
        type: string        
      vlanId:
        type: string     
        
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: solo.solo_plugin.port.create
        delete:
          implementation: solo.solo_plugin.port.delete            