tosca_definitions_version: cloudify_dsl_1_3

plugins:
  my_plugin:
    executor: central_deployment_agent
    source: https://github.com/NiltonDuarte/CloudifyPlugin/archive/master.zip
    package_name: my_plugin
    package_version: '0.0'

node_types:

  cloudify.my_plugin.nodes.VirtualNetwork:
    derived_from: cloudify.nodes.Root
    properties:
      server_ip:
        default: ''
        type: string
      server_port:
        default: ''
        type: string
      vNet_name:
        default: ''
        type: string 
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: my_plugin_pkg.my_plugin.start
                 