tosca_definitions_version: cloudify_dsl_1_3

plugins:
  my_plugin:
    executor: central_deployment_agent
    source: https://github.com/NiltonDuarte/CloudifyPlugin/archive/master.zip
    package_name: solo
    package_version: '0.0'

data_types:
  cloudify.solo.types.configuration:
    properties:
      server_ip:
        type: string
      server_port:
        type: string
      username:
        type: string
      password:
        type: string

node_types:

  cloudify.solo.nodes.VirtualNetwork:
    derived_from: cloudify.nodes.Root
    properties: 
      vNet_name:
        type: string 
        default: ''
      solo_config:
        type: cloudify.solo.types.configuration
        default: {}      
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: solo.solo_plugin.network.create
        delete:
          implementation: solo.solo_plugin.network.delete
                 